### ISSUE TITLE
Special Characters in Password Causes Invalid Credentials Error

### ISSUE THREAD

**Issue by Ressnn** [tastyware/tastytrade#122]
Having an "@" and a "!" in a password the causes following error:

```
validate_response(response)  # throws exception if not 200
  File "C:\ProgramData\mambaforge\lib\site-packages\tastytrade\utils.py", line 47, in validate_response
    raise TastytradeError(error_message)
tastytrade.utils.TastytradeError: invalid_credentials: Invalid login, please check your username and password. Unique customer support identifier:
```

**Comment by Graeme22** [comment]
I highly doubt the problem is special characters in your password. Have you tried:
- Double checking the username/password combination is correct?
- Making sure you're using the right kind of session? (Production for real accounts, certification for sandbox accounts)
- Making sure you're opted in to the API? https://manage.tastytrade.com/#/profile/developer

**Comment by Ressnn** [comment]
You are right, it was likely something else. Last night, I created the issue because I was getting login errors until I changed my password to one that didn't have special characters. When I changed it back to one with special characters, I got login errors again. However, I can't recreate it as of this morning.
