### ISSUE TITLE
Streaming candles on futures after-hours

### ISSUE THREAD

**Issue by jackroc97** [tastyware/tastytrade#179]
I am having trouble streaming candles for futures in after-hours.  I have tried the code listed below, based on some of the examples provided:

```python
async def main():
    session = Session('my_username', 'my_password')
    async with DXLinkStreamer(session) as streamer:
        await streamer.subscribe_candle(['/ES'], '15s', datetime.now(), extended_trading_hours=True)
        async for candle in streamer.listen(Candle):
            print(candle)
        
asyncio.run(main())
```

My code executes but no candles are ever printed.  I am running this during the extended hours for ES trading.

**Comment by Graeme22** [comment]
Hello! The problem here is twofold:
First, you're just using the symbol `/ES`, which is ambiguous as there are a whole host of futures under that family. One you could try that's currently active is `/ESZ4`.
Second, the streamer uses a different symbology than Tasty. So the way to handle this is to first make a call to Tasty to get the streamer symbol, then use that to subscribe to quotes/candles like so:
```python
from tastytrade.instruments import Future
future = Future.get_future(session, '/ESZ4')
# ...
await streamer.subscribe_candle([future.streamer_symbol], '15s', datetime(2024,12,1,0,0), extended_trading_hours=True)
async for candle in streamer.listen(Candle):
    print(candle)
```
If you want an algorithmic way of getting the future instead of using its symbol, you can use `tastytrade.instruments.FutureProduct` which will work with just the base symbol (`/ES`) and return which month codes are currently active.
Hope this helps!

**Comment by jackroc97** [comment]
Thanks for the quick reply @Graeme22 !  That works perfectly.

**Comment by Graeme22** [comment]
Great! If you're willing to add something like that to the documentation for posterity, that would be appreciated. Good luck trading!
