### ISSUE TITLE
Readme.md example code is not executable

### ISSUE THREAD

**Issue by avion23** [tastyware/tastytrade#5]
Readme.md code is not executed with several errors

- First problem: indentation is incorrect: ```TabError: inconsistent use of tabs and spaces in indentation```
- You can even see this in github, adding ```print(f'Received item: {quote}')``` broke the code
- Second problem: the code is a mix of old and new, caused by a refactoring in c7d2d3b6
- In the current version ```sub_values``` does not exist, but it is used
- A comparison with c7d2d3b6 shows me that there is a lot of refactoring.

Is it possible to either revert this change or insert a working version?

**Comment by avion23** [comment]
Executing this script with intendation yields
```
Number of active orders: 0
Exception in main loop
Traceback (most recent call last):
  File "/Users/avion/Documents/programming/trading/tasty/tastyworks/main.py", line 94, in <module>
    task for task in asyncio.Task.all_tasks() if not task.done()
AttributeError: type object '_asyncio.Task' has no attribute 'all_tasks'
```
So there are more errors

**Comment by avion23** [comment]
I've added https://github.com/tastyware/tastyworks-api/pull/6

**Comment by Graeme22** [comment]
Hey! Sorry for the delayed response.

I'm currently completely rewriting the API. As part of the rewrite, we'll have actual documentation and examples that work. So, I won't accept the PRs as the next release will have much improved documentation.

However, I'll leave this issue open for now, so that in the meantime people can reference the PRs if they can't get things working. Thanks for your contributions, they're always welcome!

**Comment by avion23** [comment]
Thank you. Your software is very welcome. I think it's in https://github.com/tastyware/tastyworks-api/pull/4/files , I'll try it out in the meantime

**Comment by Graeme22** [comment]
Readme code is now functional!
